export const MENU_ACTION = 'MENU_ACTION'
export const PDF_UPLOAD_ACTION = "PDF_UPLOAD_ACTION"
export const PDF_EDITING_ACTION = "PDF_EDITING_ACTION"
export const PDF_DOWNLOAD_ACTION = 'PDF_DOWNLOAD_ACTION'

export const SIGN_SAVE_ACTION = "SIGN_SAVE_ACTION"
export const SIGN_CHOOSE_ACTION = "SIGN_CHOOSE_ACTION"